### ISSUE TITLE
Dataset seems to be no longer available

### ISSUE THREAD

**Issue by nimarek** [psychoinformatics-de/studyforrest-data-visualrois#6] opened 2023-04-12 10:22 UTC
tldr; Dataset seems to be no longer available.

Hi nice people of the Psychoinformatics Lab,

 `datalad clone` leads to the following error message:

![Screenshot from 2023-04-12 12-21-28](https://user-images.githubusercontent.com/41046308/231429721-135faef8-34e2-4a0a-81d0-a041bf5846fa.png)

Is there a way to make the dataset available to the public again?
Many thanks and greetings,

Nico

**Comment by adswa** [comment] 2023-04-13 11:53
Hello Nico, and likewise greetings to beautiful Magdeburg (cough)!

I believe the problem is the ``mddatasrc`` git-type special remote in that dataset.
Let me summon a few people who can help in figuring out what's wrong (@bpoldrack, @aqw) . 


This is the ``remote.log``:

```
9536f86d-eb34-42ed-8ffc-fafd63a2b87e autoenable=true location=http://psydata.ovgu.de/studyforrest/visualrois/.git name=mddatasrc type=git timestamp=1459405007.225384s
db2e8480-0894-4e67-93b3-28d0d64d629b autoenable=true location=http://psydata.ovgu.de/studyforrest/freesurfer/.git name=mddatasrc type=git timestamp=1455197498.339419s
ea71d260-a10c-42ce-8864-826598ebc5d0 archive-id=92e65958-4a5a-4c34-a4f4-ee070f7a123b autoenable=true encryption=none externaltype=ora name=inm7-storage push-url=ria+ssh://bulk1.htc.inm7.de/ds/studyforrest/srv type=external url=ria+http://studyforrest.ds.inm7.de timestamp=1620022412.297466098s
fdb6d635-1e66-44c6-9644-08ab5010b108 autoenable=true location=https://gin.g-node.org/studyforrest/visual-areas.git name=gin type=git timestamp=1620018744.768192901s
```

There are two mddatasrc, one seemingly for the wrong dataset (?) (freesurfer), and both pointing to the long dead psydata.ovgu.de.
It seems to stand in the way of any git-annex operation:

```
❱ git annex -d -v get --from origin sub-01                                                                                                   130 !
[2023-04-13 13:51:00.136988229] (Utility.Process) process [145214] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","git-annex"]
[2023-04-13 13:51:00.142131255] (Utility.Process) process [145214] done ExitSuccess
[2023-04-13 13:51:00.143257501] (Utility.Process) process [145215] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","--hash","refs/heads/git-annex"]
[2023-04-13 13:51:00.146887459] (Utility.Process) process [145215] done ExitSuccess
[2023-04-13 13:51:00.148465269] (Utility.Process) process [145216] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","log","refs/heads/git-annex..3c151c972f9443dbbbcf58c190ed7940cd33af36","--pretty=%H","-n1"]
[2023-04-13 13:51:00.151805729] (Utility.Process) process [145216] done ExitSuccess
[2023-04-13 13:51:00.152461323] (Utility.Process) process [145217] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","log","refs/heads/git-annex..9dd5b1b7d608b599d5c22056f7e232b9d34de7a1","--pretty=%H","-n1"]
[2023-04-13 13:51:00.155713524] (Utility.Process) process [145217] done ExitSuccess
[2023-04-13 13:51:00.156696041] (Utility.Process) process [145218] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch"]
[2023-04-13 13:51:00.186954842] (Utility.Url) Request {
  host                 = "psydata.ovgu.de"
  port                 = 80
  secure               = False
  requestHeaders       = [("Accept-Encoding","identity"),("User-Agent","git-annex/10.20221003")]
  path                 = "/studyforrest/visualrois/.git/config"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
  proxySecureMode      = ProxySecureWithConnect
}
[nothing]
```

```
❱ git annex -d -v info                                                                                                                       130 !
[2023-04-13 13:52:12.789317547] (Utility.Process) process [145266] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","git-annex"]
[2023-04-13 13:52:12.791716171] (Utility.Process) process [145266] done ExitSuccess
[2023-04-13 13:52:12.792390491] (Utility.Process) process [145267] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","--hash","refs/heads/git-annex"]
[2023-04-13 13:52:12.794613765] (Utility.Process) process [145267] done ExitSuccess
[2023-04-13 13:52:12.795422515] (Utility.Process) process [145268] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","log","refs/heads/git-annex..3c151c972f9443dbbbcf58c190ed7940cd33af36","--pretty=%H","-n1"]
[2023-04-13 13:52:12.797964045] (Utility.Process) process [145268] done ExitSuccess
[2023-04-13 13:52:12.798792294] (Utility.Process) process [145269] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","log","refs/heads/git-annex..9dd5b1b7d608b599d5c22056f7e232b9d34de7a1","--pretty=%H","-n1"]
[2023-04-13 13:52:12.801146909] (Utility.Process) process [145269] done ExitSuccess
[2023-04-13 13:52:12.802609892] (Utility.Process) process [145270] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch"]
[2023-04-13 13:52:12.837329237] (Utility.Url) Request {
  host                 = "psydata.ovgu.de"
  port                 = 80
  secure               = False
  requestHeaders       = [("Accept-Encoding","identity"),("User-Agent","git-annex/10.20221003")]
  path                 = "/studyforrest/visualrois/.git/config"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
  proxySecureMode      = ProxySecureWithConnect
}
[endless waiting]
```

I believe we need to update that special remote to make everything functional again. It sadly even affects the copies of this dataset hosted on datapub and gin.

**Comment by aqw** [comment] 2023-04-13 12:07
Great to hear from you Nico!

Yeah; it's unfortunate that IPSY chose to not maintain the redirects. That broke a few things (NeuroDebian included). :-/

Sadly, there's not much I can contribute here, as the hosts are simply gone. This needs to be solved either at the special remote layer, or by updating the datasets to know the data's new locations.

Waving sunshine and rainbows in your general direction. :-D

**Comment by adswa** [comment] 2023-04-13 12:24
As a quick fix to get you going, I'd suggest that you clone the dataset from Gin, and configure your clone to ignore ``mddatasrc``:

```
datalad clone git@gin.g-node.org:/studyforrest/visual-areas.git
cd visual-areas
git config remote.mddatasrc.annex-ignore true
```

afterwards, you should be able to get the files. But we need to fix this dataset here on GitHub properly, so that it becomes functional again.

**Comment by adswa** [comment] 2023-04-14 14:55
Hello, @nimarek  I pushed a fix that should make the data available again for you. You will still see a few errors during clone, like this:

```
❱ datalad clone git@github.com:psychoinformatics-de/studyforrest-data-visualrois.git
[INFO   ] scanning for annexed files (this may take some time)                                                                                                            
[INFO   ] Unable to parse git config from origin                                                                                                                          
[INFO   ] Remote origin does not have git-annex installed; setting annex-ignore 
[INFO   ] This could be a problem with the git-annex installation on the remote. Please make sure that git-annex-shell is available in PATH when you ssh into the remote. Once you have fixed the git-annex installation, run: git annex enableremote origin 
[INFO   ] error: remote mddatasrc already exists. 
[INFO   ] git [Param "remote",Param "add",Param "mddatasrc",Param "https://datapub.fz-juelich.de/studyforrest/studyforrest/freesurfer/.git"] failed 
[INFO   ] RIA store unavailable. -caused by- Failed to access http://studyforrest.ds.inm7.de/ria-layout-version -caused by- Failed to access http://studyforrest.ds.inm7.de/ria-layout-version -caused by- Failed to establish a new session 1 times.  -caused by- HTTPConnectionPool(host='studyforrest.ds.inm7.de', port=80): Max retries exceeded with url: /ria-layout-version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f92ee73b150>: Failed to establish a new connection: [Errno -2] Name or service not known')) 
```

but data access should be restored, and everything shouldn't take minutes anymore when you clone. 

The dataset doesn't play nicely with the second ``mddatasrc``, so I'll have to look into that still - its only an annoying error though, so less urgent than the data access.

**Comment by adswa** [comment] 2023-04-14 14:56
Closing this issue as resolved (please reopen if errors persist or new ones occur). I'll track the ``mddatasrc`` issue in `studyforrest-data`

**Closed as completed by adswa** 2023-04-14 14:56 UTC

**Comment by vivekkumarcs** [comment] 2023-04-19 18:01
Hi @adswa, I am try to access the dataset as you have suggested but, I am facing some issues. It seems that I do not have access rights to that repository. I have attached the screenshot of the error that I am getting.
![issue](https://user-images.githubusercontent.com/49411216/233160971-a64aeacc-8081-47a4-a5a3-2e61baca1891.png)

And @nimarek are you able to access the datasets now?

**Comment by adswa** [comment] 2023-04-19 18:47
Hey @vivekkumarcs this is not a data access issue, the permission error comes from github.com. I suspect you are cloing using the SSH URL but you either don't have an SSH key associated with your GitHub account, or you don't have the private key on the machine you are using? You can try the repos HTTPS URL instead, this should solve your issue.
